services:
  overloadweb:
    image: overloadweb
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["python", "-m", "debugpy", "--wait-for-client", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "overload_web.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    working_dir: /app
    ports:
      - "8000:8000"
      - "5678:5678"
    develop:
      watch:
        - action: sync
          path: .
          target: /app